### ISSUE TITLE
멋쟁이 사자처럼 1주차 코드리뷰

### ISSUE THREAD

**Issue by Low-ProFiles** [8150093/likelion_intro#1]
우선 과제하시느라 고생 많으셨습니다!

 처음에 Hello Who am I?에서 곡률이 들어가 조금 더 보기 좋았던 거 같아요! 그리고 `container`, `card`, `card-1`, `card-2`로 div를 구분하여 어떻게 div가 쌓이는지를 볼 수 있어서 좋았던 거 같습니다! 😄  

조금의 피드백을 드리자면, 이미지 파일들이 본인의 **Local**에 들어가있어요! 자기소개 페이지 폴더 안에 **images 폴더**를 만들어주시고 그 안에 사진을 넣은 후, ` img src`의 경로 **수정**이 필요해 보입니다! 현재 img 파일이 저에게는 없기 때문에 사진이 보이지 않네요 😂  
![image](https://user-images.githubusercontent.com/69390311/161904255-db0b17df-5f95-4935-bd55-74cf39f88969.png)

그리고 `pole`, `pororo`, `cook`, `trip`은 **같은 속성**을 가지고 있기 때문에 하나의 class 만 선언 후에 **재사용** 하는 것이 좋습니다! `text-align: center;`를 사용하여 이미지들을 중앙 정렬하셨는데 `div class = "row"`를 사용해보시는 것도 추천드립니다 👍

**Comment by 8150093** [comment]
아아 자기소개 페이지 폴더 안에 images폴더를 만들어서 넣어야 다른 사람들에게도 보일 수 있구나 저한테는 계속 잘 보여서 몰랐어요 감사합니다! 
원래는 사진을 동그랗게 하고싶었는데 찾아서 따라해도 잘 안되서 그냥 사각형으로 했는데 방법이 있을까요??

**Comment by Low-ProFiles** [comment]
> 아아 자기소개 페이지 폴더 안에 images폴더를 만들어서 넣어야 다른 사람들에게도 보일 수 있구나 저한테는 계속 잘 보여서 몰랐어요 감사합니다! 원래는 사진을 동그랗게 하고싶었는데 찾아서 따라해도 잘 안되서 그냥 사각형으로 했는데 방법이 있을까요??

**Comment by Low-ProFiles** [comment]
따로 css에 속성을 주지 않고도 `<img style="" ... />`를 통해서 HTML에서 바로 CSS 속성을 줄 수 있어요! 사진을 동그랗게 하기 위해서는 `border-radius`에 대해 한 번 검색해보시기 바랍니다 😄
